# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taranveer Bains
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Taranveer Bains. A BBA candidate who loves to code and design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://taran.bus.sfu.ca/" # the base hostname & protocol for your site
github_username:  tearingItUp786

# Build settings
markdown: kramdown
exclude: ['node_modules', '.sass-cache', '_sass']
